### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by oit63** [islenbo/autossh#9]
系统 mac os 10.13.6
go 版本1.6.2 和 1.11.1试过 

`./autossh -c ./config.json`

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
autossh/core.params.Get(0x1211e14, 0x2, 0x1211e16)
	/Users/linbo/develop/golang/src/autossh/core/params.go:23 +0x280
main.main()
	/Users/linbo/develop/golang/src/autossh/main.go:25 +0x783
```

**Comment by noopsfun** [comment]
可能是配置文件中中文注释的问题，可以删除注释再试一下，另外不要-c指定配置文件，把配置文件和可执行程序放到同一目录直接执行可执行文件。
我的是这个问题，你可以尝试一下

**Comment by oit63** [comment]
还真是中文注释的问题@ITgladiator, 感谢，差点就弃了
